jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"


  odc-backend:
    machine: true
    steps:
      - checkout

      - run: docker run --rm --volume $(pwd):/src --volume $(pwd)/data:/usr/share/dependency-check/data --volume $(pwd)/reports:/report owasp/dependency-check --scan /src --format "CSV" --project "Webgoat" --failOnCVSS 8 --out /report
      
      - store_artifacts:
          path: reports/dependency-check-report2.csv
          destination: depcheck-artifact

workflows:
  version: 2
  webgoat:
    jobs:
      - build
      - test:
          requires:
            - build
      - odc-backend:
          requires:
            - test
